### ISSUE TITLE
[BUG] Loopback pool attribute processing crash

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2405]
Lab:
```YAML
---

addressing:
  lb_pool:
    ipv4: 10.0.0.0/24
    allocation: sequential

nodes:
  n1:
    loopback.pool: lb_pool
```

Result:
```
Traceback (most recent call last):
  File "/home/jvanbemmel/netlab/netlab", line 14, in <module>
    netsim.cli.lab_commands(__file__)
  File "/home/jvanbemmel/netlab/netsim/cli/__init__.py", line 449, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jvanbemmel/netlab/netsim/cli/create.py", line 81, in run
    augment.main.transform(topology)
  File "/home/jvanbemmel/netlab/netsim/augment/main.py", line 131, in transform
    transform_data(topology)
  File "/home/jvanbemmel/netlab/netsim/augment/main.py", line 92, in transform_data
    augment.nodes.transform(topology,topology.defaults,topology.pools)
  File "/home/jvanbemmel/netlab/netsim/augment/nodes.py", line 492, in transform
    augment_loopback_interface(n,pools,topology)
  File "/home/jvanbemmel/netlab/netsim/augment/nodes.py", line 241, in augment_loopback_interface
    if prefix_list[af].prefixlen == prefix_list[af].max_prefixlen:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'prefixlen'
```

Issue is here: https://github.com/ipspace/netlab/blob/792d26c9dbb3bc782f925a1a293cf3bd5f3fc7e7/netsim/augment/nodes.py#L230

**Comment by ipspace** [comment]
Probably caused by d78a3f6526f731f0af70ab633bf319adbda8fccd, so I'll own it and fix it ;)

**Comment by ipspace** [comment]
Root cause: nobody ever expected to see "allocation" in a loopback pool because it wouldn't do what you want it to do anyway.

I do have to change the code to do the magic only for IPv4 and IPv6 though.
